* Angular and HTMX solutions to 7 GUIs

Solutions to this: https://eugenkiss.github.io/7guis/tasks/

** Infos

Note that the Angular code assumes that the Java Sprint Boot server runs at http://localhost:8083 - but if it is not running, that's fine as well, the pure Angular components will still work just fine.

In development, I develop the Angular version first to have the UI going and then I jump into =Intellij= and code the entire backend solution there. The HTMX is initiated like this, for example in =src/app/flight-booker-htmx/flight-booker-htmx.component.html=:

#+begin_src html
<form class="flex items-center" id="div-flight-booker"
      hx-get="http://localhost:8083/flight-booker-update"
      hx-trigger="load">
</form>
#+end_src

The 7 GUI tasks are not optimal for HTMX, as all user interactions lead to one network call to the backend. Still, on localhost, I surprisingly do not see any noticeable negative impact and I enjoy the HTMX pure solutions more, since Java is just quite good!

* TODOs

- deploy Angular on Github Pages?
- show demo screenshots or videos?
- finish all tasks (3/7 done)
- add tests for the non HTMX Components
- brush over DRY principal everywhere
