* Angular and HTMX solutions to 7 GUIs

Solutions to this: https://eugenkiss.github.io/7guis/tasks/

** Infos

Note that the Angular code assumes that the Java Sprint Boot server runs at http://localhost:8083 - but if it is not running, that's fine as well; the pure Angular components will still work just fine.

In development, I develop the Angular version first to have the UI going and then I jump into =Intellij= and code the entire backend solution over there. The HTMX is initiated like this, for example in =src/app/flight-booker-htmx/flight-booker-htmx.component.html=:

#+begin_src html
<form class="flex items-center" id="div-flight-booker"
      hx-get="http://localhost:8083/flight-booker-update"
      hx-trigger="load">
</form>
#+end_src

The 7 GUI tasks are not optimal for HTMX as all user interactions result in a network call to the backend. Nevertheless, I surprisingly don't see any noticeable negative effects on the localhost and I enjoy the pure HTMX solutions more, as Java is fun to work with!

* Java backend

The backend uses Spring Boot 3.1.5, Java 17, Gradle and Thymeleaf 3.1.2 and starts on port 8083 when launched.

* TODOs

- deploy Angular on Github Pages with CI?
- show demo screenshots or videos?
- finish all tasks (3/7 done)
- add tests for the non HTMX Components
- brush over DRY principal everywhere
